version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_NAME=mydb
      - POSTGRES_USER=rsmnarts
      - POSTGRES_PASSWORD=rahasia